### ISSUE TITLE
Singletons for locations?

### ISSUE THREAD

**Issue by michaelpj** [gshen42/HasChor#13]
It seems to me from reading the paper that you could use `singletons` to simplify things a bit, e.g.

```haskell
-- bonus: be kind-polymorphic over the location kind?
data a @ (l :: k) = Located { at :: Sing l, value :: Maybe a }

-- can pattern match on the `a @ l` to work out the source, no need for the proxy
(~>) :: a @ l -> Sing l' -> a @ l'
```

I'd need to try it out to see if it runs into difficulties when constructing located values, but I think it could potentially remove a lot of noise from the surface level programs?

**Comment by gshen42** [comment]
Thanks for the suggestion!

The same simplicity could probably also be achieved by utilizing *visible type applications*. Here's the type of `comm` (another name for `~>`) for the [async branch](https://github.com/gshen42/HasChor/tree/async) I'm working on:
``` haskell 
comm ::
  forall s r {ls} {m} {a}.
  (Typeable s, Typeable r, Member s ls, Member r ls, Show a, Read a) =>
  ((Unwrappable s) => m a) ->
  Choreo ls m (Async a @ r)
comm act = perform (Comm @s @r act)
``` 
The sender and receiver are now purely types, and `comm` can be used as:
``` haskell
x <- comm @Alice @Bob someValueAtAlice
x <- comm @_ @Bob someValueAtAlice -- can omit Alice because it's in the type of the value
```
And we have full power of Haskell's type inference facility. In some cases, the receiver might not even needed.

Visible type application also allow us to pattern match on these type-level locations:
``` haskell
handler (Comm @s @r act) = undefined
```
I think this solution probably works better, although `singletons` seems like a very powerful library that I'd like to use it someday :-)

**Comment by michaelpj** [comment]
> Visible type application also allow us to pattern match on these type-level locations

Well, they allow you to _bind_ them as type variables, they don't let you _match_ on them. But then since you're using `Proxy` you clearly don't rely on matching on them, so maybe that's all you need.

_Possibly_ being able to actually inspect the location for a `@` value at the value level might let you make the wrapping and unwrapping more typesafe, but that's a different problem!
